org.jetbrains.kotlin.jvm=kotlin
org.jetbrains.kotlin.android=kotlin-android
org.jetbrains.kotlin.multiplatform=kotlin-multiplatform
org.jetbrains.kotlin.js=kotlin-js
org.jetbrains.kotlin.native=kotlin-native
com.android.application=android-application
com.android.library=android-library

